package cn.ch1tanda.event.model;

import java.util.Date;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.id
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.gmt_created
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.gmt_modified
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.gmt_deleted
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    private Date gmtDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.remark
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.username
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authority.authority
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    private String authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.id
     *
     * @return the value of authority.id
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.id
     *
     * @param id the value for authority.id
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.gmt_created
     *
     * @return the value of authority.gmt_created
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.gmt_created
     *
     * @param gmtCreated the value for authority.gmt_created
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.gmt_modified
     *
     * @return the value of authority.gmt_modified
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.gmt_modified
     *
     * @param gmtModified the value for authority.gmt_modified
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.gmt_deleted
     *
     * @return the value of authority.gmt_deleted
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public Date getGmtDeleted() {
        return gmtDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.gmt_deleted
     *
     * @param gmtDeleted the value for authority.gmt_deleted
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public void setGmtDeleted(Date gmtDeleted) {
        this.gmtDeleted = gmtDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.remark
     *
     * @return the value of authority.remark
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.remark
     *
     * @param remark the value for authority.remark
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.username
     *
     * @return the value of authority.username
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.username
     *
     * @param username the value for authority.username
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authority.authority
     *
     * @return the value of authority.authority
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authority.authority
     *
     * @param authority the value for authority.authority
     *
     * @mbg.generated Wed Jul 13 23:55:47 GMT+08:00 2022
     */
    public void setAuthority(String authority) {
        this.authority = authority;
    }
}